// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Pogodoc/pogodoc-go/client/internal"
)

type GenerateTemplatePreviewsRequest struct {
	// Type of template to be rendered
	Type GenerateTemplatePreviewsRequestType `json:"type" url:"-"`
	// Sample data for the template
	Data map[string]interface{} `json:"data,omitempty" url:"-"`
	// Format options for the rendered document
	FormatOpts *GenerateTemplatePreviewsRequestFormatOpts `json:"formatOpts,omitempty" url:"-"`
}

type GetUserTemplatesRequest struct {
	// Category of the template
	Category *GetUserTemplatesRequestCategory `json:"-" url:"category,omitempty"`
	// Search by title or description
	Search *string `json:"-" url:"search,omitempty"`
	// Type of template to be rendered
	Type *GetUserTemplatesRequestType `json:"-" url:"type,omitempty"`
	// Sort order
	Sort *GetUserTemplatesRequestSort `json:"-" url:"sort,omitempty"`
}

type SaveCreatedTemplateRequest struct {
	TemplateInfo *SaveCreatedTemplateRequestTemplateInfo `json:"templateInfo,omitempty" url:"-"`
	PreviewIds   *SaveCreatedTemplateRequestPreviewIds   `json:"previewIds,omitempty" url:"-"`
}

type CloneTemplateResponse struct {
	// ID of the new template
	NewTemplateId string `json:"newTemplateId" url:"newTemplateId"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CloneTemplateResponse) GetNewTemplateId() string {
	if c == nil {
		return ""
	}
	return c.NewTemplateId
}

func (c *CloneTemplateResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CloneTemplateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CloneTemplateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CloneTemplateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CloneTemplateResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type DeleteTemplateResponse struct {
	TemplateId string `json:"templateId" url:"templateId"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteTemplateResponse) GetTemplateId() string {
	if d == nil {
		return ""
	}
	return d.TemplateId
}

func (d *DeleteTemplateResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeleteTemplateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteTemplateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteTemplateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteTemplateResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type GeneratePresignedGetUrlResponse struct {
	// Presigned URL to get the template
	PresignedUrl string `json:"presignedUrl" url:"presignedUrl"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GeneratePresignedGetUrlResponse) GetPresignedUrl() string {
	if g == nil {
		return ""
	}
	return g.PresignedUrl
}

func (g *GeneratePresignedGetUrlResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GeneratePresignedGetUrlResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GeneratePresignedGetUrlResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GeneratePresignedGetUrlResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GeneratePresignedGetUrlResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Format options for the rendered document
type GenerateTemplatePreviewsRequestFormatOpts struct {
	FromPage *float64                                         `json:"fromPage,omitempty" url:"fromPage,omitempty"`
	ToPage   *float64                                         `json:"toPage,omitempty" url:"toPage,omitempty"`
	Format   *GenerateTemplatePreviewsRequestFormatOptsFormat `json:"format,omitempty" url:"format,omitempty"`
	// Selector to wait for to know when the page is loaded and can be saved as pdf, png, etc.
	WaitForSelector *string                                               `json:"waitForSelector,omitempty" url:"waitForSelector,omitempty"`
	Orientation     *GenerateTemplatePreviewsRequestFormatOptsOrientation `json:"orientation,omitempty" url:"orientation,omitempty"`
	Dimensions      *GenerateTemplatePreviewsRequestFormatOptsDimensions  `json:"dimensions,omitempty" url:"dimensions,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) GetFromPage() *float64 {
	if g == nil {
		return nil
	}
	return g.FromPage
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) GetToPage() *float64 {
	if g == nil {
		return nil
	}
	return g.ToPage
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) GetFormat() *GenerateTemplatePreviewsRequestFormatOptsFormat {
	if g == nil {
		return nil
	}
	return g.Format
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) GetWaitForSelector() *string {
	if g == nil {
		return nil
	}
	return g.WaitForSelector
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) GetOrientation() *GenerateTemplatePreviewsRequestFormatOptsOrientation {
	if g == nil {
		return nil
	}
	return g.Orientation
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) GetDimensions() *GenerateTemplatePreviewsRequestFormatOptsDimensions {
	if g == nil {
		return nil
	}
	return g.Dimensions
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) UnmarshalJSON(data []byte) error {
	type unmarshaler GenerateTemplatePreviewsRequestFormatOpts
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GenerateTemplatePreviewsRequestFormatOpts(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GenerateTemplatePreviewsRequestFormatOpts) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GenerateTemplatePreviewsRequestFormatOptsDimensions struct {
	Width  float64 `json:"width" url:"width"`
	Height float64 `json:"height" url:"height"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GenerateTemplatePreviewsRequestFormatOptsDimensions) GetWidth() float64 {
	if g == nil {
		return 0
	}
	return g.Width
}

func (g *GenerateTemplatePreviewsRequestFormatOptsDimensions) GetHeight() float64 {
	if g == nil {
		return 0
	}
	return g.Height
}

func (g *GenerateTemplatePreviewsRequestFormatOptsDimensions) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GenerateTemplatePreviewsRequestFormatOptsDimensions) UnmarshalJSON(data []byte) error {
	type unmarshaler GenerateTemplatePreviewsRequestFormatOptsDimensions
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GenerateTemplatePreviewsRequestFormatOptsDimensions(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GenerateTemplatePreviewsRequestFormatOptsDimensions) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GenerateTemplatePreviewsRequestFormatOptsFormat string

const (
	GenerateTemplatePreviewsRequestFormatOptsFormatLetter  GenerateTemplatePreviewsRequestFormatOptsFormat = "letter"
	GenerateTemplatePreviewsRequestFormatOptsFormatLegal   GenerateTemplatePreviewsRequestFormatOptsFormat = "legal"
	GenerateTemplatePreviewsRequestFormatOptsFormatTabloid GenerateTemplatePreviewsRequestFormatOptsFormat = "tabloid"
	GenerateTemplatePreviewsRequestFormatOptsFormatLedger  GenerateTemplatePreviewsRequestFormatOptsFormat = "ledger"
	GenerateTemplatePreviewsRequestFormatOptsFormatA0      GenerateTemplatePreviewsRequestFormatOptsFormat = "a0"
	GenerateTemplatePreviewsRequestFormatOptsFormatA1      GenerateTemplatePreviewsRequestFormatOptsFormat = "a1"
	GenerateTemplatePreviewsRequestFormatOptsFormatA2      GenerateTemplatePreviewsRequestFormatOptsFormat = "a2"
	GenerateTemplatePreviewsRequestFormatOptsFormatA3      GenerateTemplatePreviewsRequestFormatOptsFormat = "a3"
	GenerateTemplatePreviewsRequestFormatOptsFormatA4      GenerateTemplatePreviewsRequestFormatOptsFormat = "a4"
	GenerateTemplatePreviewsRequestFormatOptsFormatA5      GenerateTemplatePreviewsRequestFormatOptsFormat = "a5"
	GenerateTemplatePreviewsRequestFormatOptsFormatA6      GenerateTemplatePreviewsRequestFormatOptsFormat = "a6"
)

func NewGenerateTemplatePreviewsRequestFormatOptsFormatFromString(s string) (GenerateTemplatePreviewsRequestFormatOptsFormat, error) {
	switch s {
	case "letter":
		return GenerateTemplatePreviewsRequestFormatOptsFormatLetter, nil
	case "legal":
		return GenerateTemplatePreviewsRequestFormatOptsFormatLegal, nil
	case "tabloid":
		return GenerateTemplatePreviewsRequestFormatOptsFormatTabloid, nil
	case "ledger":
		return GenerateTemplatePreviewsRequestFormatOptsFormatLedger, nil
	case "a0":
		return GenerateTemplatePreviewsRequestFormatOptsFormatA0, nil
	case "a1":
		return GenerateTemplatePreviewsRequestFormatOptsFormatA1, nil
	case "a2":
		return GenerateTemplatePreviewsRequestFormatOptsFormatA2, nil
	case "a3":
		return GenerateTemplatePreviewsRequestFormatOptsFormatA3, nil
	case "a4":
		return GenerateTemplatePreviewsRequestFormatOptsFormatA4, nil
	case "a5":
		return GenerateTemplatePreviewsRequestFormatOptsFormatA5, nil
	case "a6":
		return GenerateTemplatePreviewsRequestFormatOptsFormatA6, nil
	}
	var t GenerateTemplatePreviewsRequestFormatOptsFormat
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GenerateTemplatePreviewsRequestFormatOptsFormat) Ptr() *GenerateTemplatePreviewsRequestFormatOptsFormat {
	return &g
}

type GenerateTemplatePreviewsRequestFormatOptsOrientation string

const (
	GenerateTemplatePreviewsRequestFormatOptsOrientationLandscape GenerateTemplatePreviewsRequestFormatOptsOrientation = "landscape"
	GenerateTemplatePreviewsRequestFormatOptsOrientationPortrait  GenerateTemplatePreviewsRequestFormatOptsOrientation = "portrait"
)

func NewGenerateTemplatePreviewsRequestFormatOptsOrientationFromString(s string) (GenerateTemplatePreviewsRequestFormatOptsOrientation, error) {
	switch s {
	case "landscape":
		return GenerateTemplatePreviewsRequestFormatOptsOrientationLandscape, nil
	case "portrait":
		return GenerateTemplatePreviewsRequestFormatOptsOrientationPortrait, nil
	}
	var t GenerateTemplatePreviewsRequestFormatOptsOrientation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GenerateTemplatePreviewsRequestFormatOptsOrientation) Ptr() *GenerateTemplatePreviewsRequestFormatOptsOrientation {
	return &g
}

// Type of template to be rendered
type GenerateTemplatePreviewsRequestType string

const (
	GenerateTemplatePreviewsRequestTypeDocx      GenerateTemplatePreviewsRequestType = "docx"
	GenerateTemplatePreviewsRequestTypeXlsx      GenerateTemplatePreviewsRequestType = "xlsx"
	GenerateTemplatePreviewsRequestTypePptx      GenerateTemplatePreviewsRequestType = "pptx"
	GenerateTemplatePreviewsRequestTypeEjs       GenerateTemplatePreviewsRequestType = "ejs"
	GenerateTemplatePreviewsRequestTypeHtml      GenerateTemplatePreviewsRequestType = "html"
	GenerateTemplatePreviewsRequestTypeLatex     GenerateTemplatePreviewsRequestType = "latex"
	GenerateTemplatePreviewsRequestTypeFramework GenerateTemplatePreviewsRequestType = "framework"
)

func NewGenerateTemplatePreviewsRequestTypeFromString(s string) (GenerateTemplatePreviewsRequestType, error) {
	switch s {
	case "docx":
		return GenerateTemplatePreviewsRequestTypeDocx, nil
	case "xlsx":
		return GenerateTemplatePreviewsRequestTypeXlsx, nil
	case "pptx":
		return GenerateTemplatePreviewsRequestTypePptx, nil
	case "ejs":
		return GenerateTemplatePreviewsRequestTypeEjs, nil
	case "html":
		return GenerateTemplatePreviewsRequestTypeHtml, nil
	case "latex":
		return GenerateTemplatePreviewsRequestTypeLatex, nil
	case "framework":
		return GenerateTemplatePreviewsRequestTypeFramework, nil
	}
	var t GenerateTemplatePreviewsRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GenerateTemplatePreviewsRequestType) Ptr() *GenerateTemplatePreviewsRequestType {
	return &g
}

type GenerateTemplatePreviewsResponse struct {
	PngPreview *GenerateTemplatePreviewsResponsePngPreview `json:"pngPreview,omitempty" url:"pngPreview,omitempty"`
	PdfPreview *GenerateTemplatePreviewsResponsePdfPreview `json:"pdfPreview,omitempty" url:"pdfPreview,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GenerateTemplatePreviewsResponse) GetPngPreview() *GenerateTemplatePreviewsResponsePngPreview {
	if g == nil {
		return nil
	}
	return g.PngPreview
}

func (g *GenerateTemplatePreviewsResponse) GetPdfPreview() *GenerateTemplatePreviewsResponsePdfPreview {
	if g == nil {
		return nil
	}
	return g.PdfPreview
}

func (g *GenerateTemplatePreviewsResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GenerateTemplatePreviewsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GenerateTemplatePreviewsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GenerateTemplatePreviewsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GenerateTemplatePreviewsResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GenerateTemplatePreviewsResponsePdfPreview struct {
	// URL of the rendered preview
	Url string `json:"url" url:"url"`
	// ID of the render job
	JobId string `json:"jobId" url:"jobId"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GenerateTemplatePreviewsResponsePdfPreview) GetUrl() string {
	if g == nil {
		return ""
	}
	return g.Url
}

func (g *GenerateTemplatePreviewsResponsePdfPreview) GetJobId() string {
	if g == nil {
		return ""
	}
	return g.JobId
}

func (g *GenerateTemplatePreviewsResponsePdfPreview) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GenerateTemplatePreviewsResponsePdfPreview) UnmarshalJSON(data []byte) error {
	type unmarshaler GenerateTemplatePreviewsResponsePdfPreview
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GenerateTemplatePreviewsResponsePdfPreview(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GenerateTemplatePreviewsResponsePdfPreview) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GenerateTemplatePreviewsResponsePngPreview struct {
	// URL of the rendered preview
	Url string `json:"url" url:"url"`
	// ID of the render job
	JobId string `json:"jobId" url:"jobId"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GenerateTemplatePreviewsResponsePngPreview) GetUrl() string {
	if g == nil {
		return ""
	}
	return g.Url
}

func (g *GenerateTemplatePreviewsResponsePngPreview) GetJobId() string {
	if g == nil {
		return ""
	}
	return g.JobId
}

func (g *GenerateTemplatePreviewsResponsePngPreview) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GenerateTemplatePreviewsResponsePngPreview) UnmarshalJSON(data []byte) error {
	type unmarshaler GenerateTemplatePreviewsResponsePngPreview
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GenerateTemplatePreviewsResponsePngPreview(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GenerateTemplatePreviewsResponsePngPreview) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetTemplateByIdResponse struct {
	// Unique ID of the template
	Uuid string `json:"uuid" url:"uuid"`
	// Title of the template
	Title string `json:"title" url:"title"`
	// Description of the template
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Type of template to be rendered
	Type GetTemplateByIdResponseType `json:"type" url:"type"`
	// Categories of the template
	Categories []string `json:"categories,omitempty" url:"categories,omitempty"`
	// Permissions of the template
	Permissions GetTemplateByIdResponsePermissions `json:"permissions" url:"permissions"`
	// Preview URL of the template
	Preview *string `json:"preview,omitempty" url:"preview,omitempty"`
	// Content ID of the template in S3
	ContentId string `json:"contentId" url:"contentId"`
	// Source code of the template
	SourceCode *string `json:"sourceCode,omitempty" url:"sourceCode,omitempty"`
	// Sample data for the template
	SampleData map[string]interface{} `json:"sampleData,omitempty" url:"sampleData,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetTemplateByIdResponse) GetUuid() string {
	if g == nil {
		return ""
	}
	return g.Uuid
}

func (g *GetTemplateByIdResponse) GetTitle() string {
	if g == nil {
		return ""
	}
	return g.Title
}

func (g *GetTemplateByIdResponse) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetTemplateByIdResponse) GetType() GetTemplateByIdResponseType {
	if g == nil {
		return ""
	}
	return g.Type
}

func (g *GetTemplateByIdResponse) GetCategories() []string {
	if g == nil {
		return nil
	}
	return g.Categories
}

func (g *GetTemplateByIdResponse) GetPermissions() GetTemplateByIdResponsePermissions {
	if g == nil {
		return ""
	}
	return g.Permissions
}

func (g *GetTemplateByIdResponse) GetPreview() *string {
	if g == nil {
		return nil
	}
	return g.Preview
}

func (g *GetTemplateByIdResponse) GetContentId() string {
	if g == nil {
		return ""
	}
	return g.ContentId
}

func (g *GetTemplateByIdResponse) GetSourceCode() *string {
	if g == nil {
		return nil
	}
	return g.SourceCode
}

func (g *GetTemplateByIdResponse) GetSampleData() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.SampleData
}

func (g *GetTemplateByIdResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetTemplateByIdResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTemplateByIdResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTemplateByIdResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTemplateByIdResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Permissions of the template
type GetTemplateByIdResponsePermissions string

const (
	GetTemplateByIdResponsePermissionsPublic  GetTemplateByIdResponsePermissions = "public"
	GetTemplateByIdResponsePermissionsPrivate GetTemplateByIdResponsePermissions = "private"
)

func NewGetTemplateByIdResponsePermissionsFromString(s string) (GetTemplateByIdResponsePermissions, error) {
	switch s {
	case "public":
		return GetTemplateByIdResponsePermissionsPublic, nil
	case "private":
		return GetTemplateByIdResponsePermissionsPrivate, nil
	}
	var t GetTemplateByIdResponsePermissions
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetTemplateByIdResponsePermissions) Ptr() *GetTemplateByIdResponsePermissions {
	return &g
}

// Type of template to be rendered
type GetTemplateByIdResponseType string

const (
	GetTemplateByIdResponseTypeDocx      GetTemplateByIdResponseType = "docx"
	GetTemplateByIdResponseTypeXlsx      GetTemplateByIdResponseType = "xlsx"
	GetTemplateByIdResponseTypePptx      GetTemplateByIdResponseType = "pptx"
	GetTemplateByIdResponseTypeEjs       GetTemplateByIdResponseType = "ejs"
	GetTemplateByIdResponseTypeHtml      GetTemplateByIdResponseType = "html"
	GetTemplateByIdResponseTypeLatex     GetTemplateByIdResponseType = "latex"
	GetTemplateByIdResponseTypeFramework GetTemplateByIdResponseType = "framework"
)

func NewGetTemplateByIdResponseTypeFromString(s string) (GetTemplateByIdResponseType, error) {
	switch s {
	case "docx":
		return GetTemplateByIdResponseTypeDocx, nil
	case "xlsx":
		return GetTemplateByIdResponseTypeXlsx, nil
	case "pptx":
		return GetTemplateByIdResponseTypePptx, nil
	case "ejs":
		return GetTemplateByIdResponseTypeEjs, nil
	case "html":
		return GetTemplateByIdResponseTypeHtml, nil
	case "latex":
		return GetTemplateByIdResponseTypeLatex, nil
	case "framework":
		return GetTemplateByIdResponseTypeFramework, nil
	}
	var t GetTemplateByIdResponseType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetTemplateByIdResponseType) Ptr() *GetTemplateByIdResponseType {
	return &g
}

type GetTemplateIndexHtmlResponse struct {
	// Index.html file of the template
	IndexHtml string `json:"indexHtml" url:"indexHtml"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetTemplateIndexHtmlResponse) GetIndexHtml() string {
	if g == nil {
		return ""
	}
	return g.IndexHtml
}

func (g *GetTemplateIndexHtmlResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetTemplateIndexHtmlResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTemplateIndexHtmlResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTemplateIndexHtmlResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTemplateIndexHtmlResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetUserTemplatesRequestCategory string

const (
	GetUserTemplatesRequestCategoryInvoice       GetUserTemplatesRequestCategory = "invoice"
	GetUserTemplatesRequestCategoryMail          GetUserTemplatesRequestCategory = "mail"
	GetUserTemplatesRequestCategoryReport        GetUserTemplatesRequestCategory = "report"
	GetUserTemplatesRequestCategoryCv            GetUserTemplatesRequestCategory = "cv"
	GetUserTemplatesRequestCategoryReceipt       GetUserTemplatesRequestCategory = "receipt"
	GetUserTemplatesRequestCategoryOrder         GetUserTemplatesRequestCategory = "order"
	GetUserTemplatesRequestCategoryContract      GetUserTemplatesRequestCategory = "contract"
	GetUserTemplatesRequestCategoryCertificate   GetUserTemplatesRequestCategory = "certificate"
	GetUserTemplatesRequestCategoryStatement     GetUserTemplatesRequestCategory = "statement"
	GetUserTemplatesRequestCategoryBrochure      GetUserTemplatesRequestCategory = "brochure"
	GetUserTemplatesRequestCategoryWarranty      GetUserTemplatesRequestCategory = "warranty"
	GetUserTemplatesRequestCategoryPoster        GetUserTemplatesRequestCategory = "poster"
	GetUserTemplatesRequestCategoryMenu          GetUserTemplatesRequestCategory = "menu"
	GetUserTemplatesRequestCategoryCatalog       GetUserTemplatesRequestCategory = "catalog"
	GetUserTemplatesRequestCategoryPackaging     GetUserTemplatesRequestCategory = "packaging"
	GetUserTemplatesRequestCategoryAdvertisement GetUserTemplatesRequestCategory = "advertisement"
	GetUserTemplatesRequestCategoryOther         GetUserTemplatesRequestCategory = "other"
	GetUserTemplatesRequestCategoryFavorite      GetUserTemplatesRequestCategory = "favorite"
)

func NewGetUserTemplatesRequestCategoryFromString(s string) (GetUserTemplatesRequestCategory, error) {
	switch s {
	case "invoice":
		return GetUserTemplatesRequestCategoryInvoice, nil
	case "mail":
		return GetUserTemplatesRequestCategoryMail, nil
	case "report":
		return GetUserTemplatesRequestCategoryReport, nil
	case "cv":
		return GetUserTemplatesRequestCategoryCv, nil
	case "receipt":
		return GetUserTemplatesRequestCategoryReceipt, nil
	case "order":
		return GetUserTemplatesRequestCategoryOrder, nil
	case "contract":
		return GetUserTemplatesRequestCategoryContract, nil
	case "certificate":
		return GetUserTemplatesRequestCategoryCertificate, nil
	case "statement":
		return GetUserTemplatesRequestCategoryStatement, nil
	case "brochure":
		return GetUserTemplatesRequestCategoryBrochure, nil
	case "warranty":
		return GetUserTemplatesRequestCategoryWarranty, nil
	case "poster":
		return GetUserTemplatesRequestCategoryPoster, nil
	case "menu":
		return GetUserTemplatesRequestCategoryMenu, nil
	case "catalog":
		return GetUserTemplatesRequestCategoryCatalog, nil
	case "packaging":
		return GetUserTemplatesRequestCategoryPackaging, nil
	case "advertisement":
		return GetUserTemplatesRequestCategoryAdvertisement, nil
	case "other":
		return GetUserTemplatesRequestCategoryOther, nil
	case "favorite":
		return GetUserTemplatesRequestCategoryFavorite, nil
	}
	var t GetUserTemplatesRequestCategory
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetUserTemplatesRequestCategory) Ptr() *GetUserTemplatesRequestCategory {
	return &g
}

type GetUserTemplatesRequestSort string

const (
	GetUserTemplatesRequestSortCreatedAtDesc GetUserTemplatesRequestSort = "createdAt:desc"
	GetUserTemplatesRequestSortCreatedAtAsc  GetUserTemplatesRequestSort = "createdAt:asc"
	GetUserTemplatesRequestSortUpdatedAtDesc GetUserTemplatesRequestSort = "updatedAt:desc"
	GetUserTemplatesRequestSortUpdatedAtAsc  GetUserTemplatesRequestSort = "updatedAt:asc"
	GetUserTemplatesRequestSortTitleAsc      GetUserTemplatesRequestSort = "title:asc"
	GetUserTemplatesRequestSortTitleDesc     GetUserTemplatesRequestSort = "title:desc"
)

func NewGetUserTemplatesRequestSortFromString(s string) (GetUserTemplatesRequestSort, error) {
	switch s {
	case "createdAt:desc":
		return GetUserTemplatesRequestSortCreatedAtDesc, nil
	case "createdAt:asc":
		return GetUserTemplatesRequestSortCreatedAtAsc, nil
	case "updatedAt:desc":
		return GetUserTemplatesRequestSortUpdatedAtDesc, nil
	case "updatedAt:asc":
		return GetUserTemplatesRequestSortUpdatedAtAsc, nil
	case "title:asc":
		return GetUserTemplatesRequestSortTitleAsc, nil
	case "title:desc":
		return GetUserTemplatesRequestSortTitleDesc, nil
	}
	var t GetUserTemplatesRequestSort
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetUserTemplatesRequestSort) Ptr() *GetUserTemplatesRequestSort {
	return &g
}

type GetUserTemplatesRequestType string

const (
	GetUserTemplatesRequestTypeDocx      GetUserTemplatesRequestType = "docx"
	GetUserTemplatesRequestTypeXlsx      GetUserTemplatesRequestType = "xlsx"
	GetUserTemplatesRequestTypePptx      GetUserTemplatesRequestType = "pptx"
	GetUserTemplatesRequestTypeEjs       GetUserTemplatesRequestType = "ejs"
	GetUserTemplatesRequestTypeHtml      GetUserTemplatesRequestType = "html"
	GetUserTemplatesRequestTypeLatex     GetUserTemplatesRequestType = "latex"
	GetUserTemplatesRequestTypeFramework GetUserTemplatesRequestType = "framework"
)

func NewGetUserTemplatesRequestTypeFromString(s string) (GetUserTemplatesRequestType, error) {
	switch s {
	case "docx":
		return GetUserTemplatesRequestTypeDocx, nil
	case "xlsx":
		return GetUserTemplatesRequestTypeXlsx, nil
	case "pptx":
		return GetUserTemplatesRequestTypePptx, nil
	case "ejs":
		return GetUserTemplatesRequestTypeEjs, nil
	case "html":
		return GetUserTemplatesRequestTypeHtml, nil
	case "latex":
		return GetUserTemplatesRequestTypeLatex, nil
	case "framework":
		return GetUserTemplatesRequestTypeFramework, nil
	}
	var t GetUserTemplatesRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetUserTemplatesRequestType) Ptr() *GetUserTemplatesRequestType {
	return &g
}

type GetUserTemplatesResponse struct {
	Templates []*GetUserTemplatesResponseTemplatesItem `json:"templates,omitempty" url:"templates,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUserTemplatesResponse) GetTemplates() []*GetUserTemplatesResponseTemplatesItem {
	if g == nil {
		return nil
	}
	return g.Templates
}

func (g *GetUserTemplatesResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUserTemplatesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUserTemplatesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUserTemplatesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUserTemplatesResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetUserTemplatesResponseTemplatesItem struct {
	Uuid        string  `json:"uuid" url:"uuid"`
	Title       string  `json:"title" url:"title"`
	Description *string `json:"description,omitempty" url:"description,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUserTemplatesResponseTemplatesItem) GetUuid() string {
	if g == nil {
		return ""
	}
	return g.Uuid
}

func (g *GetUserTemplatesResponseTemplatesItem) GetTitle() string {
	if g == nil {
		return ""
	}
	return g.Title
}

func (g *GetUserTemplatesResponseTemplatesItem) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetUserTemplatesResponseTemplatesItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUserTemplatesResponseTemplatesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUserTemplatesResponseTemplatesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUserTemplatesResponseTemplatesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUserTemplatesResponseTemplatesItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type InitializeTemplateCreationResponse struct {
	// ID of the template
	TemplateId string `json:"templateId" url:"templateId"`
	// Presigned URL to upload the template to S3
	PresignedTemplateUploadUrl string `json:"presignedTemplateUploadUrl" url:"presignedTemplateUploadUrl"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InitializeTemplateCreationResponse) GetTemplateId() string {
	if i == nil {
		return ""
	}
	return i.TemplateId
}

func (i *InitializeTemplateCreationResponse) GetPresignedTemplateUploadUrl() string {
	if i == nil {
		return ""
	}
	return i.PresignedTemplateUploadUrl
}

func (i *InitializeTemplateCreationResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InitializeTemplateCreationResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InitializeTemplateCreationResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InitializeTemplateCreationResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InitializeTemplateCreationResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type SaveCreatedTemplateRequestPreviewIds struct {
	// ID of the job for the PNG preview
	PngJobId string `json:"pngJobId" url:"pngJobId"`
	// ID of the job for the PDF preview
	PdfJobId string `json:"pdfJobId" url:"pdfJobId"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SaveCreatedTemplateRequestPreviewIds) GetPngJobId() string {
	if s == nil {
		return ""
	}
	return s.PngJobId
}

func (s *SaveCreatedTemplateRequestPreviewIds) GetPdfJobId() string {
	if s == nil {
		return ""
	}
	return s.PdfJobId
}

func (s *SaveCreatedTemplateRequestPreviewIds) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SaveCreatedTemplateRequestPreviewIds) UnmarshalJSON(data []byte) error {
	type unmarshaler SaveCreatedTemplateRequestPreviewIds
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SaveCreatedTemplateRequestPreviewIds(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SaveCreatedTemplateRequestPreviewIds) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SaveCreatedTemplateRequestTemplateInfo struct {
	// Title of the template
	Title string `json:"title" url:"title"`
	// Description of the template
	Description string `json:"description" url:"description"`
	// Type of template to be rendered
	Type SaveCreatedTemplateRequestTemplateInfoType `json:"type" url:"type"`
	// Sample data for the template
	SampleData map[string]interface{} `json:"sampleData,omitempty" url:"sampleData,omitempty"`
	SourceCode *string                `json:"sourceCode,omitempty" url:"sourceCode,omitempty"`
	// Categories of the template
	Categories  []SaveCreatedTemplateRequestTemplateInfoCategoriesItem `json:"categories,omitempty" url:"categories,omitempty"`
	Orientation *SaveCreatedTemplateRequestTemplateInfoOrientation     `json:"orientation,omitempty" url:"orientation,omitempty"`
	Dimensions  *SaveCreatedTemplateRequestTemplateInfoDimensions      `json:"dimensions,omitempty" url:"dimensions,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetTitle() string {
	if s == nil {
		return ""
	}
	return s.Title
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetType() SaveCreatedTemplateRequestTemplateInfoType {
	if s == nil {
		return ""
	}
	return s.Type
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetSampleData() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.SampleData
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetSourceCode() *string {
	if s == nil {
		return nil
	}
	return s.SourceCode
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetCategories() []SaveCreatedTemplateRequestTemplateInfoCategoriesItem {
	if s == nil {
		return nil
	}
	return s.Categories
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetOrientation() *SaveCreatedTemplateRequestTemplateInfoOrientation {
	if s == nil {
		return nil
	}
	return s.Orientation
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetDimensions() *SaveCreatedTemplateRequestTemplateInfoDimensions {
	if s == nil {
		return nil
	}
	return s.Dimensions
}

func (s *SaveCreatedTemplateRequestTemplateInfo) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SaveCreatedTemplateRequestTemplateInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler SaveCreatedTemplateRequestTemplateInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SaveCreatedTemplateRequestTemplateInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SaveCreatedTemplateRequestTemplateInfo) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Category of the template
type SaveCreatedTemplateRequestTemplateInfoCategoriesItem string

const (
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemInvoice       SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "invoice"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemMail          SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "mail"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemReport        SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "report"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemCv            SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "cv"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemReceipt       SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "receipt"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemOrder         SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "order"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemContract      SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "contract"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemCertificate   SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "certificate"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemStatement     SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "statement"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemBrochure      SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "brochure"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemWarranty      SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "warranty"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemPoster        SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "poster"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemMenu          SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "menu"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemCatalog       SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "catalog"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemPackaging     SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "packaging"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemAdvertisement SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "advertisement"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemOther         SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "other"
	SaveCreatedTemplateRequestTemplateInfoCategoriesItemFavorite      SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "favorite"
)

func NewSaveCreatedTemplateRequestTemplateInfoCategoriesItemFromString(s string) (SaveCreatedTemplateRequestTemplateInfoCategoriesItem, error) {
	switch s {
	case "invoice":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemInvoice, nil
	case "mail":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemMail, nil
	case "report":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemReport, nil
	case "cv":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemCv, nil
	case "receipt":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemReceipt, nil
	case "order":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemOrder, nil
	case "contract":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemContract, nil
	case "certificate":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemCertificate, nil
	case "statement":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemStatement, nil
	case "brochure":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemBrochure, nil
	case "warranty":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemWarranty, nil
	case "poster":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemPoster, nil
	case "menu":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemMenu, nil
	case "catalog":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemCatalog, nil
	case "packaging":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemPackaging, nil
	case "advertisement":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemAdvertisement, nil
	case "other":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemOther, nil
	case "favorite":
		return SaveCreatedTemplateRequestTemplateInfoCategoriesItemFavorite, nil
	}
	var t SaveCreatedTemplateRequestTemplateInfoCategoriesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SaveCreatedTemplateRequestTemplateInfoCategoriesItem) Ptr() *SaveCreatedTemplateRequestTemplateInfoCategoriesItem {
	return &s
}

type SaveCreatedTemplateRequestTemplateInfoDimensions struct {
	Width  float64 `json:"width" url:"width"`
	Height float64 `json:"height" url:"height"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SaveCreatedTemplateRequestTemplateInfoDimensions) GetWidth() float64 {
	if s == nil {
		return 0
	}
	return s.Width
}

func (s *SaveCreatedTemplateRequestTemplateInfoDimensions) GetHeight() float64 {
	if s == nil {
		return 0
	}
	return s.Height
}

func (s *SaveCreatedTemplateRequestTemplateInfoDimensions) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SaveCreatedTemplateRequestTemplateInfoDimensions) UnmarshalJSON(data []byte) error {
	type unmarshaler SaveCreatedTemplateRequestTemplateInfoDimensions
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SaveCreatedTemplateRequestTemplateInfoDimensions(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SaveCreatedTemplateRequestTemplateInfoDimensions) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SaveCreatedTemplateRequestTemplateInfoOrientation string

const (
	SaveCreatedTemplateRequestTemplateInfoOrientationLandscape SaveCreatedTemplateRequestTemplateInfoOrientation = "landscape"
	SaveCreatedTemplateRequestTemplateInfoOrientationPortrait  SaveCreatedTemplateRequestTemplateInfoOrientation = "portrait"
)

func NewSaveCreatedTemplateRequestTemplateInfoOrientationFromString(s string) (SaveCreatedTemplateRequestTemplateInfoOrientation, error) {
	switch s {
	case "landscape":
		return SaveCreatedTemplateRequestTemplateInfoOrientationLandscape, nil
	case "portrait":
		return SaveCreatedTemplateRequestTemplateInfoOrientationPortrait, nil
	}
	var t SaveCreatedTemplateRequestTemplateInfoOrientation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SaveCreatedTemplateRequestTemplateInfoOrientation) Ptr() *SaveCreatedTemplateRequestTemplateInfoOrientation {
	return &s
}

// Type of template to be rendered
type SaveCreatedTemplateRequestTemplateInfoType string

const (
	SaveCreatedTemplateRequestTemplateInfoTypeDocx      SaveCreatedTemplateRequestTemplateInfoType = "docx"
	SaveCreatedTemplateRequestTemplateInfoTypeXlsx      SaveCreatedTemplateRequestTemplateInfoType = "xlsx"
	SaveCreatedTemplateRequestTemplateInfoTypePptx      SaveCreatedTemplateRequestTemplateInfoType = "pptx"
	SaveCreatedTemplateRequestTemplateInfoTypeEjs       SaveCreatedTemplateRequestTemplateInfoType = "ejs"
	SaveCreatedTemplateRequestTemplateInfoTypeHtml      SaveCreatedTemplateRequestTemplateInfoType = "html"
	SaveCreatedTemplateRequestTemplateInfoTypeLatex     SaveCreatedTemplateRequestTemplateInfoType = "latex"
	SaveCreatedTemplateRequestTemplateInfoTypeFramework SaveCreatedTemplateRequestTemplateInfoType = "framework"
)

func NewSaveCreatedTemplateRequestTemplateInfoTypeFromString(s string) (SaveCreatedTemplateRequestTemplateInfoType, error) {
	switch s {
	case "docx":
		return SaveCreatedTemplateRequestTemplateInfoTypeDocx, nil
	case "xlsx":
		return SaveCreatedTemplateRequestTemplateInfoTypeXlsx, nil
	case "pptx":
		return SaveCreatedTemplateRequestTemplateInfoTypePptx, nil
	case "ejs":
		return SaveCreatedTemplateRequestTemplateInfoTypeEjs, nil
	case "html":
		return SaveCreatedTemplateRequestTemplateInfoTypeHtml, nil
	case "latex":
		return SaveCreatedTemplateRequestTemplateInfoTypeLatex, nil
	case "framework":
		return SaveCreatedTemplateRequestTemplateInfoTypeFramework, nil
	}
	var t SaveCreatedTemplateRequestTemplateInfoType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SaveCreatedTemplateRequestTemplateInfoType) Ptr() *SaveCreatedTemplateRequestTemplateInfoType {
	return &s
}

type UpdateTemplateRequestPreviewIds struct {
	PngJobId string `json:"pngJobId" url:"pngJobId"`
	PdfJobId string `json:"pdfJobId" url:"pdfJobId"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateTemplateRequestPreviewIds) GetPngJobId() string {
	if u == nil {
		return ""
	}
	return u.PngJobId
}

func (u *UpdateTemplateRequestPreviewIds) GetPdfJobId() string {
	if u == nil {
		return ""
	}
	return u.PdfJobId
}

func (u *UpdateTemplateRequestPreviewIds) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateTemplateRequestPreviewIds) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateTemplateRequestPreviewIds
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateTemplateRequestPreviewIds(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateTemplateRequestPreviewIds) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateTemplateRequestTemplateInfo struct {
	// Title of the template
	Title *string `json:"title,omitempty" url:"title,omitempty"`
	// Description of the template
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Type of template to be rendered
	Type *UpdateTemplateRequestTemplateInfoType `json:"type,omitempty" url:"type,omitempty"`
	// Sample data for the template
	SampleData map[string]interface{} `json:"sampleData,omitempty" url:"sampleData,omitempty"`
	SourceCode *string                `json:"sourceCode,omitempty" url:"sourceCode,omitempty"`
	// Categories of the template
	Categories  []UpdateTemplateRequestTemplateInfoCategoriesItem `json:"categories,omitempty" url:"categories,omitempty"`
	Orientation *UpdateTemplateRequestTemplateInfoOrientation     `json:"orientation,omitempty" url:"orientation,omitempty"`
	Dimensions  *UpdateTemplateRequestTemplateInfoDimensions      `json:"dimensions,omitempty" url:"dimensions,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateTemplateRequestTemplateInfo) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdateTemplateRequestTemplateInfo) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateTemplateRequestTemplateInfo) GetType() *UpdateTemplateRequestTemplateInfoType {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UpdateTemplateRequestTemplateInfo) GetSampleData() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.SampleData
}

func (u *UpdateTemplateRequestTemplateInfo) GetSourceCode() *string {
	if u == nil {
		return nil
	}
	return u.SourceCode
}

func (u *UpdateTemplateRequestTemplateInfo) GetCategories() []UpdateTemplateRequestTemplateInfoCategoriesItem {
	if u == nil {
		return nil
	}
	return u.Categories
}

func (u *UpdateTemplateRequestTemplateInfo) GetOrientation() *UpdateTemplateRequestTemplateInfoOrientation {
	if u == nil {
		return nil
	}
	return u.Orientation
}

func (u *UpdateTemplateRequestTemplateInfo) GetDimensions() *UpdateTemplateRequestTemplateInfoDimensions {
	if u == nil {
		return nil
	}
	return u.Dimensions
}

func (u *UpdateTemplateRequestTemplateInfo) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateTemplateRequestTemplateInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateTemplateRequestTemplateInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateTemplateRequestTemplateInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateTemplateRequestTemplateInfo) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Category of the template
type UpdateTemplateRequestTemplateInfoCategoriesItem string

const (
	UpdateTemplateRequestTemplateInfoCategoriesItemInvoice       UpdateTemplateRequestTemplateInfoCategoriesItem = "invoice"
	UpdateTemplateRequestTemplateInfoCategoriesItemMail          UpdateTemplateRequestTemplateInfoCategoriesItem = "mail"
	UpdateTemplateRequestTemplateInfoCategoriesItemReport        UpdateTemplateRequestTemplateInfoCategoriesItem = "report"
	UpdateTemplateRequestTemplateInfoCategoriesItemCv            UpdateTemplateRequestTemplateInfoCategoriesItem = "cv"
	UpdateTemplateRequestTemplateInfoCategoriesItemReceipt       UpdateTemplateRequestTemplateInfoCategoriesItem = "receipt"
	UpdateTemplateRequestTemplateInfoCategoriesItemOrder         UpdateTemplateRequestTemplateInfoCategoriesItem = "order"
	UpdateTemplateRequestTemplateInfoCategoriesItemContract      UpdateTemplateRequestTemplateInfoCategoriesItem = "contract"
	UpdateTemplateRequestTemplateInfoCategoriesItemCertificate   UpdateTemplateRequestTemplateInfoCategoriesItem = "certificate"
	UpdateTemplateRequestTemplateInfoCategoriesItemStatement     UpdateTemplateRequestTemplateInfoCategoriesItem = "statement"
	UpdateTemplateRequestTemplateInfoCategoriesItemBrochure      UpdateTemplateRequestTemplateInfoCategoriesItem = "brochure"
	UpdateTemplateRequestTemplateInfoCategoriesItemWarranty      UpdateTemplateRequestTemplateInfoCategoriesItem = "warranty"
	UpdateTemplateRequestTemplateInfoCategoriesItemPoster        UpdateTemplateRequestTemplateInfoCategoriesItem = "poster"
	UpdateTemplateRequestTemplateInfoCategoriesItemMenu          UpdateTemplateRequestTemplateInfoCategoriesItem = "menu"
	UpdateTemplateRequestTemplateInfoCategoriesItemCatalog       UpdateTemplateRequestTemplateInfoCategoriesItem = "catalog"
	UpdateTemplateRequestTemplateInfoCategoriesItemPackaging     UpdateTemplateRequestTemplateInfoCategoriesItem = "packaging"
	UpdateTemplateRequestTemplateInfoCategoriesItemAdvertisement UpdateTemplateRequestTemplateInfoCategoriesItem = "advertisement"
	UpdateTemplateRequestTemplateInfoCategoriesItemOther         UpdateTemplateRequestTemplateInfoCategoriesItem = "other"
	UpdateTemplateRequestTemplateInfoCategoriesItemFavorite      UpdateTemplateRequestTemplateInfoCategoriesItem = "favorite"
)

func NewUpdateTemplateRequestTemplateInfoCategoriesItemFromString(s string) (UpdateTemplateRequestTemplateInfoCategoriesItem, error) {
	switch s {
	case "invoice":
		return UpdateTemplateRequestTemplateInfoCategoriesItemInvoice, nil
	case "mail":
		return UpdateTemplateRequestTemplateInfoCategoriesItemMail, nil
	case "report":
		return UpdateTemplateRequestTemplateInfoCategoriesItemReport, nil
	case "cv":
		return UpdateTemplateRequestTemplateInfoCategoriesItemCv, nil
	case "receipt":
		return UpdateTemplateRequestTemplateInfoCategoriesItemReceipt, nil
	case "order":
		return UpdateTemplateRequestTemplateInfoCategoriesItemOrder, nil
	case "contract":
		return UpdateTemplateRequestTemplateInfoCategoriesItemContract, nil
	case "certificate":
		return UpdateTemplateRequestTemplateInfoCategoriesItemCertificate, nil
	case "statement":
		return UpdateTemplateRequestTemplateInfoCategoriesItemStatement, nil
	case "brochure":
		return UpdateTemplateRequestTemplateInfoCategoriesItemBrochure, nil
	case "warranty":
		return UpdateTemplateRequestTemplateInfoCategoriesItemWarranty, nil
	case "poster":
		return UpdateTemplateRequestTemplateInfoCategoriesItemPoster, nil
	case "menu":
		return UpdateTemplateRequestTemplateInfoCategoriesItemMenu, nil
	case "catalog":
		return UpdateTemplateRequestTemplateInfoCategoriesItemCatalog, nil
	case "packaging":
		return UpdateTemplateRequestTemplateInfoCategoriesItemPackaging, nil
	case "advertisement":
		return UpdateTemplateRequestTemplateInfoCategoriesItemAdvertisement, nil
	case "other":
		return UpdateTemplateRequestTemplateInfoCategoriesItemOther, nil
	case "favorite":
		return UpdateTemplateRequestTemplateInfoCategoriesItemFavorite, nil
	}
	var t UpdateTemplateRequestTemplateInfoCategoriesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateTemplateRequestTemplateInfoCategoriesItem) Ptr() *UpdateTemplateRequestTemplateInfoCategoriesItem {
	return &u
}

type UpdateTemplateRequestTemplateInfoDimensions struct {
	Width  float64 `json:"width" url:"width"`
	Height float64 `json:"height" url:"height"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateTemplateRequestTemplateInfoDimensions) GetWidth() float64 {
	if u == nil {
		return 0
	}
	return u.Width
}

func (u *UpdateTemplateRequestTemplateInfoDimensions) GetHeight() float64 {
	if u == nil {
		return 0
	}
	return u.Height
}

func (u *UpdateTemplateRequestTemplateInfoDimensions) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateTemplateRequestTemplateInfoDimensions) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateTemplateRequestTemplateInfoDimensions
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateTemplateRequestTemplateInfoDimensions(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateTemplateRequestTemplateInfoDimensions) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateTemplateRequestTemplateInfoOrientation string

const (
	UpdateTemplateRequestTemplateInfoOrientationLandscape UpdateTemplateRequestTemplateInfoOrientation = "landscape"
	UpdateTemplateRequestTemplateInfoOrientationPortrait  UpdateTemplateRequestTemplateInfoOrientation = "portrait"
)

func NewUpdateTemplateRequestTemplateInfoOrientationFromString(s string) (UpdateTemplateRequestTemplateInfoOrientation, error) {
	switch s {
	case "landscape":
		return UpdateTemplateRequestTemplateInfoOrientationLandscape, nil
	case "portrait":
		return UpdateTemplateRequestTemplateInfoOrientationPortrait, nil
	}
	var t UpdateTemplateRequestTemplateInfoOrientation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateTemplateRequestTemplateInfoOrientation) Ptr() *UpdateTemplateRequestTemplateInfoOrientation {
	return &u
}

// Type of template to be rendered
type UpdateTemplateRequestTemplateInfoType string

const (
	UpdateTemplateRequestTemplateInfoTypeDocx      UpdateTemplateRequestTemplateInfoType = "docx"
	UpdateTemplateRequestTemplateInfoTypeXlsx      UpdateTemplateRequestTemplateInfoType = "xlsx"
	UpdateTemplateRequestTemplateInfoTypePptx      UpdateTemplateRequestTemplateInfoType = "pptx"
	UpdateTemplateRequestTemplateInfoTypeEjs       UpdateTemplateRequestTemplateInfoType = "ejs"
	UpdateTemplateRequestTemplateInfoTypeHtml      UpdateTemplateRequestTemplateInfoType = "html"
	UpdateTemplateRequestTemplateInfoTypeLatex     UpdateTemplateRequestTemplateInfoType = "latex"
	UpdateTemplateRequestTemplateInfoTypeFramework UpdateTemplateRequestTemplateInfoType = "framework"
)

func NewUpdateTemplateRequestTemplateInfoTypeFromString(s string) (UpdateTemplateRequestTemplateInfoType, error) {
	switch s {
	case "docx":
		return UpdateTemplateRequestTemplateInfoTypeDocx, nil
	case "xlsx":
		return UpdateTemplateRequestTemplateInfoTypeXlsx, nil
	case "pptx":
		return UpdateTemplateRequestTemplateInfoTypePptx, nil
	case "ejs":
		return UpdateTemplateRequestTemplateInfoTypeEjs, nil
	case "html":
		return UpdateTemplateRequestTemplateInfoTypeHtml, nil
	case "latex":
		return UpdateTemplateRequestTemplateInfoTypeLatex, nil
	case "framework":
		return UpdateTemplateRequestTemplateInfoTypeFramework, nil
	}
	var t UpdateTemplateRequestTemplateInfoType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateTemplateRequestTemplateInfoType) Ptr() *UpdateTemplateRequestTemplateInfoType {
	return &u
}

type UpdateTemplateResponse struct {
	NewContentId *string `json:"newContentId,omitempty" url:"newContentId,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateTemplateResponse) GetNewContentId() *string {
	if u == nil {
		return nil
	}
	return u.NewContentId
}

func (u *UpdateTemplateResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateTemplateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateTemplateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateTemplateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateTemplateResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateTemplateRequest struct {
	TemplateInfo *UpdateTemplateRequestTemplateInfo `json:"templateInfo,omitempty" url:"-"`
	PreviewIds   *UpdateTemplateRequestPreviewIds   `json:"previewIds,omitempty" url:"-"`
	// ID by which the new template content is saved
	ContentId *string `json:"contentId,omitempty" url:"-"`
}

type UploadTemplateIndexHtmlRequest struct {
	// New index.html file of the template
	IndexHtml string `json:"indexHtml" url:"-"`
}
