name: publish

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Pack SDK
        working-directory: ./Pogodoc.SDK
        run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}/Pogodoc.SDK.*.nupkg
          if-no-files-found: error
          retention-days: 7

  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: create_nuget
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Publish NuGet package
        run: |
          dotnet nuget push "${{ env.NuGetDirectory }}/Pogodoc.SDK.*.nupkg" `
            --api-key "${{ secrets.NUGET_APIKEY }}" `
            --source https://api.nuget.org/v3/index.json `
            --skip-duplicate
